# Dockerfile.frontend
FROM nginx:alpine

# Удаляем дефолтный конфиг Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Копируем наш кастомный конфиг Nginx
COPY nginx.conf /etc/nginx/conf.d/video_service.conf

# Копируем файлы фронтенда
COPY app/frontend/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]