# Dockerfile.backend
FROM python:3.13-slim

WORKDIR /app

# Копируем pyproject.toml и устанавливаем зависимости
COPY pyproject.toml .
COPY uv.lock .
RUN pip install --no-cache-dir -e .
COPY alembic.ini .
COPY alembic/ ./alembic/
# Копируем остальное приложение
COPY app/ /app/app
ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8000

# Команда для запуска Миграций и Uvicorn
CMD ["sh", "-c", "alembic upgrade head && python -m app.backend.main"]
