"""Create playlists table

Revision ID: 6f4e39f1bb9b
Revises: 5f5e39f1bb9a
Create Date: 2026-03-02 17:45:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f4e39f1bb9b"
down_revision: Union[str, Sequence[str], None] = "4189b6b22fed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("folder_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playlists_folder_path"), "playlists", ["folder_path"], unique=True
    )
    op.create_index(op.f("ix_playlists_id"), "playlists", ["id"], unique=False)
    op.create_index(op.f("ix_playlists_name"), "playlists", ["name"], unique=False)

    # Add playlist_id column to videos table
    op.add_column("videos", sa.Column("playlist_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "videos", "playlists", ["playlist_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "videos", type_="foreignkey")
    op.drop_column("videos", "playlist_id")
    op.drop_index(op.f("ix_playlists_name"), table_name="playlists")
    op.drop_index(op.f("ix_playlists_id"), table_name="playlists")
    op.drop_index(op.f("ix_playlists_folder_path"), table_name="playlists")
    op.drop_table("playlists")
    # ### end Alembic commands ###
